import { useState } from 'react';
import { useAdminTable } from './useAdminTable';
import { useSaveForm } from './useSaveForm';
import { ErrorNote, FormActions, PageHeader, RowActions } from './ui';
import { churchContact } from '../data/contact';

function SettingsForm({ settings, onSave }) {
  const defaults = { address: churchContact.address, email: churchContact.email, phone: churchContact.phone, phone_display: churchContact.phoneDisplay, whatsapp_url: churchContact.whatsappUrl, facebook_url: churchContact.facebookUrl, youtube_url: churchContact.youtubeUrl, map_embed_url: churchContact.mapEmbedUrl, directions_url: churchContact.directionsUrl };
  const [values, setValues] = useState({ ...defaults, ...settings }); const { saving, error, submit } = useSaveForm(onSave); const set = (field) => (event) => setValues((current) => ({ ...current, [field]: event.target.value }));
  const fields = [['address', 'Address'], ['email', 'Email'], ['phone', 'Phone number'], ['phone_display', 'Phone number display'], ['whatsapp_url', 'WhatsApp URL'], ['facebook_url', 'Facebook URL'], ['youtube_url', 'YouTube URL'], ['directions_url', 'Directions URL'], ['map_embed_url', 'Google Maps embed URL']];
  return <form onSubmit={(event) => submit(event, Object.fromEntries(fields.map(([key]) => [key, values[key].trim() || null])))} className="bg-white rounded-xl border border-gray-200 p-5 sm:p-6 space-y-4"><p className="text-sm text-charcoal/70">These details appear on the Contact page. Visitor messages below are private and available only to signed-in admins.</p><div className="grid sm:grid-cols-2 gap-4">{fields.map(([key, label]) => <div key={key} className={key === 'address' || key === 'map_embed_url' ? 'sm:col-span-2' : ''}><label htmlFor={`contact-setting-${key}`} className="form-label">{label}</label><input id={`contact-setting-${key}`} type={key.endsWith('_url') ? 'url' : key === 'email' ? 'email' : 'text'} required={['address', 'email', 'phone', 'phone_display'].includes(key)} value={values[key] ?? ''} onChange={set(key)} className="form-input" /></div>)}</div><FormActions saving={saving} error={error} /></form>;
}

export default function ContactAdmin() {
  const settings = useAdminTable('contact_settings'); const messages = useAdminTable('contact_messages'); const [actionError, setActionError] = useState('');
  const save = async (values) => { const current = settings.rows[0]; if (current) await settings.mutate((q) => q.update({ ...values, updated_at: new Date().toISOString() }).eq('id', current.id)); else await settings.mutate((q) => q.insert({ id: true, ...values })); };
  const run = async (action, label) => { try { setActionError(''); await action(); } catch (err) { setActionError(`${label}: ${err.message}`); } };
  return <><PageHeader title="Contact" description="Update contact details and read messages sent through the website." /><ErrorNote>{settings.error || messages.error || actionError}</ErrorNote><SettingsForm key={settings.rows[0]?.id ?? 'loading'} settings={settings.rows[0]} onSave={save} /><section className="mt-10"><h2 className="text-lg mb-1">Messages</h2><p className="text-sm text-charcoal/60 mb-3">Newest first. Marking a message as read is visible only to admins.</p>{!messages.loading && !messages.rows.length ? <div className="rounded-xl border-2 border-dashed border-gray-200 bg-white px-6 py-10 text-center text-charcoal/70">No messages yet.</div> : <ul className="bg-white rounded-xl border border-gray-200 divide-y divide-gray-100">{messages.rows.map((message) => <li key={message.id} className={`p-4 ${message.is_read ? '' : 'bg-gold/5'}`}><div className="flex gap-3"><div className="min-w-0 flex-1"><p className="font-semibold text-royal">{message.name} {!message.is_read && <span className="ml-2 text-xs font-sans uppercase tracking-wide text-gold">New</span>}</p><p className="text-sm text-charcoal/70 break-all">{message.email}{message.phone && ` · ${message.phone}`}</p><p className="text-sm text-charcoal whitespace-pre-wrap mt-2">{message.message}</p><p className="text-xs text-charcoal/50 mt-2">{new Date(message.created_at).toLocaleString()}</p></div><RowActions name={`message from ${message.name}`} editLabel={message.is_read ? 'Mark message as unread' : 'Mark message as read'} onEdit={() => run(() => messages.mutate((q) => q.update({ is_read: !message.is_read }).eq('id', message.id)), "Couldn't update message")} onDelete={() => window.confirm('Delete this message? This cannot be undone.') && run(() => messages.mutate((q) => q.delete().eq('id', message.id)), "Couldn't delete message")} /></div></li>)}</ul>}</section></>;
}
