import { useState } from 'react';
import Modal from '../components/Modal';
import { useAdminTable } from './useAdminTable';
import { useSaveForm } from './useSaveForm';
import { AddIcon, EmptyState, ErrorNote, FormActions, PageHeader, RowActions } from './ui';

function GivingForm({ method, onSave, onCancel }) {
  const [values, setValues] = useState({ kind: method.kind ?? 'bank', provider: method.provider ?? '', label: method.label ?? '', value: method.value ?? '' });
  const { saving, error, submit } = useSaveForm(onSave); const set = (field) => (e) => setValues((current) => ({ ...current, [field]: e.target.value }));
  return <form onSubmit={(e) => submit(e, Object.fromEntries(Object.entries(values).map(([key, value]) => [key, value.trim ? value.trim() : value])))} className="space-y-5"><div><label htmlFor="giving-kind" className="form-label">Method</label><select id="giving-kind" value={values.kind} onChange={set('kind')} className="form-input"><option value="bank">Bank transfer</option><option value="mobile">Mobile money</option></select></div><div><label htmlFor="giving-provider" className="form-label">{values.kind === 'bank' ? 'Bank name' : 'Provider'}</label><input id="giving-provider" required value={values.provider} onChange={set('provider')} className="form-input" /></div><div><label htmlFor="giving-label" className="form-label">{values.kind === 'bank' ? 'Account name' : 'Number label'}</label><input id="giving-label" required value={values.label} onChange={set('label')} placeholder={values.kind === 'bank' ? 'Katoto Revival Center' : 'Phone number'} className="form-input" /></div><div><label htmlFor="giving-value" className="form-label">{values.kind === 'bank' ? 'Account number' : 'Number or merchant code'}</label><input id="giving-value" required value={values.value} onChange={set('value')} className="form-input" /></div><FormActions saving={saving} onCancel={onCancel} error={error} /></form>;
}

export default function GivingAdmin() {
  const { rows, loading, error, mutate, reorder, nextSortOrder } = useAdminTable('giving_methods'); const [editing, setEditing] = useState(null); const [actionError, setActionError] = useState('');
  const save = async (values) => { if (editing.id) await mutate((q) => q.update(values).eq('id', editing.id)); else await mutate((q) => q.insert({ ...values, sort_order: nextSortOrder })); setEditing(null); };
  const run = async (action, label) => { try { setActionError(''); await action(); } catch (err) { setActionError(`${label}: ${err.message}`); } };
  const remove = (method) => { if (window.confirm(`Delete “${method.provider}”? This can’t be undone.`)) run(() => mutate((q) => q.delete().eq('id', method.id)), "Couldn't delete"); };
  return <><PageHeader title="Give" description="Manage the bank and mobile-money details displayed on the Give page." action={<button type="button" onClick={() => setEditing({})} className="btn-primary"><AddIcon /> Add giving method</button>} /><ErrorNote>{error || actionError}</ErrorNote>{!loading && !rows.length && !error && <EmptyState>No giving methods yet.</EmptyState>}{rows.length > 0 && <ol className="bg-white rounded-xl border border-gray-200 divide-y divide-gray-100">{rows.map((method, index) => <li key={method.id} className="flex items-center gap-3 p-3 sm:p-4"><div className="min-w-0 flex-1"><p className="font-semibold text-royal truncate">{method.provider} <span className="text-xs font-sans font-medium text-charcoal/50">{method.kind === 'bank' ? 'Bank' : 'Mobile money'}</span></p><p className="text-sm text-charcoal/70 truncate">{method.label}: {method.value}</p></div><RowActions name={method.provider} onMoveUp={index > 0 ? () => run(() => reorder(index, index - 1), "Couldn't reorder") : null} onMoveDown={index < rows.length - 1 ? () => run(() => reorder(index, index + 1), "Couldn't reorder") : null} onEdit={() => setEditing(method)} onDelete={() => remove(method)} /></li>)}</ol>}<Modal isOpen={editing !== null} onClose={() => setEditing(null)} title={editing?.id ? 'Edit giving method' : 'Add giving method'} size="small">{editing && <GivingForm key={editing.id ?? 'new'} method={editing} onSave={save} onCancel={() => setEditing(null)} />}</Modal></>;
}
