import { useState } from 'react';
import { useAdminTable } from './useAdminTable';
import { ErrorNote, PageHeader, RowActions } from './ui';

export default function PrayerAdmin() {
  const { rows, loading, error, mutate } = useAdminTable('prayer_requests'); const [actionError, setActionError] = useState('');
  const run = async (action, label) => { try { setActionError(''); await action(); } catch (err) { setActionError(`${label}: ${err.message}`); } };
  const publish = (request) => run(() => mutate((q) => q.update({ approved_at: request.approved_at ? null : new Date().toISOString() }).eq('id', request.id)), "Couldn't update request");
  return <><PageHeader title="Prayer" description="Read prayer requests and choose which shared requests may appear on the public prayer wall." /><ErrorNote>{error || actionError}</ErrorNote>{!loading && !rows.length ? <div className="rounded-xl border-2 border-dashed border-gray-200 bg-white px-6 py-10 text-center text-charcoal/70">No prayer requests yet.</div> : <ul className="bg-white rounded-xl border border-gray-200 divide-y divide-gray-100">{rows.map((request) => <li key={request.id} className="p-4"><div className="flex gap-3"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-royal">{request.name || 'Anonymous'}</p>{request.share_public ? <span className={`text-xs font-semibold uppercase tracking-wide ${request.approved_at ? 'text-green-700' : 'text-gold'}`}>{request.approved_at ? 'Published' : 'Awaiting approval'}</span> : <span className="text-xs font-semibold uppercase tracking-wide text-charcoal/50">Private</span>}</div>{request.email && <p className="text-sm text-charcoal/70 break-all">{request.email}</p>}<p className="text-sm text-charcoal whitespace-pre-wrap mt-2">{request.request}</p><p className="text-xs text-charcoal/50 mt-2">{new Date(request.created_at).toLocaleString()}</p></div><div className="flex flex-col gap-1 flex-shrink-0">{request.share_public && <button type="button" onClick={() => publish(request)} className="min-h-[44px] px-3 rounded-lg text-sm font-medium text-royal hover:bg-gray-100">{request.approved_at ? 'Hide' : 'Publish'}</button>}<RowActions name="prayer request" onEdit={undefined} onDelete={() => window.confirm('Delete this prayer request? This cannot be undone.') && run(() => mutate((q) => q.delete().eq('id', request.id)), "Couldn't delete request")} /></div></div></li>)}</ul>}</>;
}
